version: '3.5'

services:
    backend:
        image: backend
        restart: always
        environment:
            - FRONT_URL=http://localhost:5000
            - REDIS=redis
            - REDIS_URL=redis://cache
            - DB_USERNAME=user
            - DB_PASSWORD=passwd
            - DB_NAME=pgdb
            - DB_HOST=postgres
        links:
            - redis
            - postgres
        ports:
            - 8000:8000
        volumes:
            - /home/paavo/frontend-example-docker/backend-example-docker/logs.txt://logs.txt

    frontend:
        image: frontend
        environment:
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
    
    redis:
        container_name: cache
        hostname: redis
        image: redis
        expose:
            - 6379
    
    postgres:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=passwd
            - POSTGRES_DB=pgdb
        ports:
            - 5432:5432
        volumes:
            - /home/paavo/frontend-example-docker/backend-example-docker/server/database:/var/lib/postgresql/data


    
